### ISSUE TITLE
Add recipe for integral components 

### ISSUE THREAD

**Issue by gfbbkon** [Elephant-on-github/Thermal-More-Integral-Components#2]
I think that needed add in confirmation file option that enabled default recipes for integral components

**Comment by Elephant-on-github** [comment]
okay i will get on that

**Comment by Elephant-on-github** [comment]
@gfbbkon I finally got round to it https://modrinth.com/mod/thermal-more-integral-components/version/1.1.0-1.20.1

**Comment by Elephant-on-github** [comment]
sorry no config

**Comment by gfbbkon** [comment]
Anyway, thanks!

**Comment by Elephant-on-github** [comment]
i put the recipes in wrong folder updating with hotfix now

**Comment by Elephant-on-github** [comment]
uploaded hotfixes (weird bug modrinth doesn't let you chose Minecraft version for some reason)

**Comment by Elephant-on-github** [comment]
still  in wrong folder XD
