### ISSUE TITLE
thoughts on 1.19?

### ISSUE THREAD

**Issue by Joliefray** [Elephant-on-github/Thermal-More-Integral-Components#3]
i just thought id ask. but
do you have a plan to port to 1.19.2? there was some modpacks i love to play i'd love to use this mod in 
just thought i could ask

**Comment by Elephant-on-github** [comment]
Sorry that it took me along time to get back to you. I will have a look at porting to 1.19 :)

**Comment by Joliefray** [comment]
no your fine. awesome thank you

**Comment by Elephant-on-github** [comment]
@Joliefray Just to let you know, I finally stopped procrastinating and have ported to 1.19. It should be available on Curseforge as soon as they finish processing it. Sorry that it took forever.
